version: '3.8'

services:
  mysql-container:
    image: mysql:8.3.0
    container_name: mysql-container-finance-api
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: finance
      MYSQL_USER: finance
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container-finance-api
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 8080:15672
      - 5672:5672
      - 25676:25676